// Maps this project's FIFA-style team codes (data/teams.csv) to ISO 3166-1 alpha-2
// codes (flagcdn.com's naming), including the UK home-nation subdivision flags
// flagcdn.com also serves (gb-eng, gb-sct).
const TEAM_ISO_CODE: Record<string, string> = {
  ARG: "ar",
  ESP: "es",
  FRA: "fr",
  ENG: "gb-eng",
  BRA: "br",
  GER: "de",
  NED: "nl",
  BEL: "be",
  POR: "pt",
  MAR: "ma",
  PAR: "py",
  UR: "uy",
  MEX: "mx",
  USA: "us",
  JPN: "jp",
  SEN: "sn",
  ITA: "it",
  CRO: "hr",
  COL: "co",
  ECU: "ec",
  DEN: "dk",
  SUI: "ch",
  KOR: "kr",
  IRN: "ir",
  CAN: "ca",
  NGA: "ng",
  EGY: "eg",
  ALG: "dz",
  AUS: "au",
  KSA: "sa",
  PAN: "pa",
  CIV: "ci",
  AUT: "at",
  TUR: "tr",
  SRB: "rs",
  NOR: "no",
  UKR: "ua",
  CHI: "cl",
  PER: "pe",
  CRC: "cr",
  JAM: "jm",
  TUN: "tn",
  CMR: "cm",
  GHA: "gh",
  MLI: "ml",
  QAT: "qa",
  UZB: "uz",
  IRQ: "iq",
  NZL: "nz",
  SWE: "se",
  POL: "pl",
  CZE: "cz",
  GRE: "gr",
  HON: "hn",
  GUA: "gt",
  RSA: "za",
  COD: "cd",
  UAE: "ae",
  JOR: "jo",
  CPV: "cv",
  CUW: "cw",
  HAI: "ht",
  SCO: "gb-sct",
  BIH: "ba",
};

export function flagUrl(teamId: string, width: 20 | 40 | 80 = 40): string | null {
  const iso = TEAM_ISO_CODE[teamId];
  if (!iso) return null;
  return `https://flagcdn.com/w${width}/${iso}.png`;
}
